import Head from 'next/head'
import Nav from '@/Components/Nav'
import {useRouter} from 'next/router';
import styled from 'styled-components';
import TaskCard from '@/Components/TaskCard';
import JohnCalendar from '@/Components/Calendar';
import Button from '@/Components/Button';
import axios from "axios";

const MyCard = (info) => {
    console.log(info);
    return <div></div>
        style={{margin:10}}
        status='basic'
        header={<Text>{info.item.title}</Text>}
        footer={<Text>{info.item.director}</Text>}>
    </Card>
}

const CalendarCont = styled.div`
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    width: 100vw;
`;

const CalendarPageCont = styled.div`
    display: flex;
    flex-direction: column;
    font-family: 'Ubuntu', sans-serif;
    width: 75rem;
    height: 40rem;
`;

const CalendarPageRow = styled.div`
    display: flex;
    width: 75rem;
    height: 35rem;
    justify-content: space-between;
    align-items: center;
`;

const Divider = styled.div`
    border-left: 2px black solid;
    height: 40rem;
    width: 2px;
    height: 35rem;
`;

const CalendarWithHeader = styled.div`
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    align-items: center;
    height: 40rem;

`;

export default function Calendar() {
    const router = useRouter();
    return (
        <CalendarCont>
            <Head>
                <title>Calendar - John</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <CalendarPageCont>
                <h1>Today</h1>
                <CalendarPageRow>
                    <TaskCard />
                    <Divider />
                    <CalendarWithHeader>
                        <h1>Calendar</h1>
                        <JohnCalendar />
                        <Button text="View All Events" routeTo="/forecast" fontsize="2rem"/>
                    </CalendarWithHeader>
                </CalendarPageRow>
            </CalendarPageCont>
        </CalendarCont>
    )
}
