import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@/Components/Button'
import EventInfoCard from '@/Components/EventInfoCard'
import Nav from '@/Components/Nav'
import styled from 'styled-components';

const MainCont = styled.div
`
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100vw;
    height: 100vh;
    background: linear-gradient(225deg, #067A53, #3FC284);
    padding: 20px;
    overflow: hidden;
    position: relative;
`

const TopBar = styled.div
` 
    display: flex;
    justify-content: flex-end;
    align-self: flex-start;
    width: 100%;
`

const MidSection = styled.div
`
    display: flex;
    width: 100%;
    justify-content: space-evenly;
    min-height: 80%;
`

const Heading = styled.h1
`
    font-family: Ubuntu, sans-serif;
    font-weight: 700;
    font-size: 5rem;
    color: #FFF; 
    margin-bottom: 0;
`

const Description = styled.p
`
    font-family: Ubuntu, sans-serif;
    font-size: 2rem;
    font-weight: 400;
    color: #FFF;
`

const Col = styled.div
`
    display: flex;
    flex-direction: column;
    flex-basis: 50%;
`

const Dorito = styled.img
`
    width: 1600px;
    height: 1300px;
    bottom: -400px;
    right: -200px;
    position: absolute;

`

export default function Landing()
{
    return (
        <MainCont>
          <Head>
            <title>Welcome to John</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Dorito src="/dorito.png"/>
          <TopBar>
            <Button width="10rem" height="2.5rem" bgcolor="#111F1C" borderradius="3rem" fontsize="1.5rem" text="Login" routeTo="/login"/>
          </TopBar>
          <MidSection>
            <Image src="/john.svg" alt="John" width="400px" height="400px" />
            <Col>
                <Heading>
                    Welcome to John
                </Heading>
                <Description>
                    Take your event planning to the next level with our state-of-the-art web application. 
                    Create events with minimal steps and easy-to-use navigation. 
                    Track costs with an implemented cost splitter that allocates split costs to attendees. 
                    Get started for free now!
                </Description>
                <Button text="SIGN UP" fontsize="2rem" routeTo="/calendar"/>
            </Col>
          </MidSection>
        </MainCont>
    )
}