import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import Button from '@/Components/Button'
import { Button } from '@mui/material'
import EventInfoCard from '@/Components/EventInfoCard'
import Nav from '@/Components/Nav'
import styled from 'styled-components'
import { TextField } from '@material-ui/core'
import { Input } from '@mui/material'
import InputLabel from '@mui/material/InputLabel';
import InputAdornment from '@mui/material/InputAdornment';
import React from 'react'
import { useState } from 'react';


const HomeCont = styled.div`
  display: flex;
  flex-direction: column;
`;

const ContentCont = styled.div
`
    padding: 20px;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
`

const RoundedCont = styled.div
`
    width: 400px;
    border: 3px solid #3FC284;
    border-radius: 32px;
    padding: 20px;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
`

const Header = styled.h1
`
    font-family: Ubuntu, sans-serif;
    font-size: 3rem;
    font-weight: 600;
    width: 400px;
    text-align: left;
`

const SubHeader = styled.h2
`
    font-family: Ubuntu, sans-serif;
    font-size: 2rem;
    font-weight: 400;
`

const Spacer = styled.div
`
    padding: 20px;
`

const ButtonCont = styled.div
`
    width: 100%;
    display: flex;
    justify-content: center;
`

const CostCont = styled.div
`
    border: 1px solid gray;
    padding: 10px;
    text-align: center;
    font-size: 14pt;
    color: gray;
`

export default function Home() {
    const [values, setValues] = React.useState({
        amount: '',
        people: ''
      });

    const handleChange = (prop) => (event) => {
        setValues({ ...values, [prop]: event.target.value });
    };

    function CalculateCost(){
        var numberofpeople = values.people;
        var totalcost = values.amount;

        var individualcost = totalcost / numberofpeople;
        console.log(individualcost);

        document.querySelector(".individcost").innerHTML = "$" + individualcost;
        document.querySelector(".individcost").style.fontSize = "24pt";
        document.querySelector(".individcost").style.color = "black";
    }

    return (
      <HomeCont>
        <Head>
          <title>Cost Splitter - John</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <ContentCont>
            <Header>Cost Splitter</Header>
            <RoundedCont>
                <Spacer />
                <InputLabel>Number of People</InputLabel>
                <Input
                    id="number"
                    type="number"
                    value={values.people}
                    onChange={handleChange('people')}
                />
                <Spacer />
                <InputLabel htmlFor="standard-adornment-amount">Amount</InputLabel>
                <Input
                    id="standard-adornment-amount"
                    value={values.amount}
                    onChange={handleChange('amount')}
                    startAdornment={<InputAdornment position="start">$</InputAdornment>}
                />
                <Spacer />
                <ButtonCont>
                    {/* <Button text="Calculate" fontsize="24pt" width="200px" height="50px" onClick={CalculateCost} /> */}
                    <Button
                        variant="contained"
                        size="large"
                        onClick={CalculateCost}>Calculate</Button>
                </ButtonCont>
                <Spacer />
                <SubHeader>Cost Per Attendee</SubHeader>
                <CostCont className="individcost">Individual cost appears here...</CostCont>
                <Spacer />
            </RoundedCont>
            </ContentCont>
      </HomeCont>
    )
  }
