import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@/Components/Button'
import EventInfoCard from '@/Components/EventInfoCard'
import Nav from '@/Components/Nav'
import styled from 'styled-components'
import { TextField } from '@material-ui/core'


const HomeCont = styled.div`
  display: flex;
  flex-direction: column;
`;

const ContentCont = styled.div
`
    padding: 20px;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
`

const RoundedCont = styled.div
`
    width: 80%;
    border: 3px solid #3FC284;
    border-radius: 32px;
    padding: 20px;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
`

const Header = styled.h1
`
    font-family: Ubuntu, sans-serif;
    font-size: 3rem;
    font-weight: 600;
    width: 80%;
    text-align: left;
`

const SubHeader = styled.h2
`
    font-family: Ubuntu, sans-serif;
    font-size: 2rem;
    font-weight: 400;
`

const Spacer = styled.div
`
    padding: 20px;
`

const ButtonCont = styled.div
`
    width: 100%;
    display: flex;
    justify-content: center;
`

export default function Home() {
    return (
      <HomeCont>
        <Head>
          <title>John</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <ContentCont>
            <Header>Event Creation</Header>
            <RoundedCont>
                <TextField id="standard-basic" label="Name your event..." variant="standard" color="primary" />
                <Spacer />
                <TextField id="standard-basic" label="Describe the event..." variant="standard" color="primary" multiline="true" />
                <Spacer />
                <SubHeader>What days will you meet?</SubHeader>
                <Spacer />
                <TextField id="standard-basic" label="Where will you meet?" variant="standard" color="primary" />
                <Spacer />
                <ButtonCont>
                    <Button text="Create Event" fontsize="24pt" />
                </ButtonCont>
            </RoundedCont>
            </ContentCont>
      </HomeCont>
    )
  }


  